const movieWebhook = {
    notification_type: "MEDIA_AUTO_APPROVED",
    media: {
        media_type: "movie",
        tmdbId: "94605",
        tvdbId: "371028",
        status: "PENDING",
        status4k: "UNKNOWN",
    },
    request: {
        request_id: "12",
        requestedBy_email: "email@email.com",
        requestedBy_username: "user2",
        requestedBy_avatar: "",
    },
    extra: [],
}

const showWebhook = {
    notification_type: "MEDIA_AUTO_APPROVED",
    media: {
        media_type: "tv",
        tmdbId: "94605",
        tvdbId: "371028",
        status: "PENDING",
        status4k: "UNKNOWN",
    },
    request: {
        request_id: "12",
        requestedBy_email: "email@email.com",
        requestedBy_username: "user2",
        requestedBy_avatar: "",
    },
    extra: [{ name: "Requested Seasons", value: "0, 1, 2" }],
}

const movieGladiator2Data = {
    id: 558449,
    adult: false,
    budget: 310000000,
    genres: [
        { id: 28, name: "Action" },
        { id: 12, name: "Adventure" },
    ],
    originalLanguage: "en",
    originalTitle: "Gladiator II",
    popularity: 1333.762,
    productionCompanies: [
        {
            id: 4,
            name: "Paramount Pictures",
            originCountry: "US",
            logoPath: "/gz66EfNoYPqHTYI4q9UEN4CbHRc.png",
        },
        {
            id: 14440,
            name: "Red Wagon Entertainment",
            originCountry: "US",
            logoPath: "/5QbaGiuxc91D6qf75JZGX6OKXoU.png",
        },
        {
            id: 49325,
            name: "Parkes+MacDonald Image Nation",
            originCountry: "US",
            logoPath: "/R05WCoCJcPWGSDaKaYgx3AeVuR.png",
        },
        {
            id: 221347,
            name: "Scott Free Productions",
            originCountry: "US",
            logoPath: "/6Ry6uNBaa0IbbSs1XYIgX5DkA9r.png",
        },
    ],
    productionCountries: [{ iso_3166_1: "US", name: "United States of America" }],
    releaseDate: "2024-11-13",
    revenue: 0,
    spokenLanguages: [{ english_name: "English", iso_639_1: "en", name: "English" }],
    status: "Released",
    title: "Gladiator II",
    video: false,
    voteAverage: 7.315,
    voteCount: 65,
    backdropPath: "/8mjYwWT50GkRrrRdyHzJorfEfcl.jpg",
    homepage: "https://www.gladiator.movie",
    imdbId: "tt9218128",
    runtime: 148,
    tagline: "Prepare to be entertained.",
    collection: {
        id: 1069584,
        name: "Gladiator Collection",
        posterPath: "/r7uyUOB6fmmPumWwHiV7Hn2kUbL.jpg",
        backdropPath: "/eCWJHiezqeSvn0aEt1kPM6Lmlhe.jpg",
    },
    externalIds: {
        facebookId: "GladiatorMovie",
        imdbId: "tt9218128",
        instagramId: "gladiatormovie",
        twitterId: "GladiatorMovie",
    },
    mediaInfo: {
        downloadStatus: [],
        downloadStatus4k: [],
        id: 8,
        mediaType: "movie",
        tmdbId: 558449,
        tvdbId: null,
        imdbId: null,
        status: 3,
        status4k: 1,
        createdAt: "2024-11-14T08:19:49.000Z",
        updatedAt: "2024-11-14T08:19:49.000Z",
        lastSeasonChange: "2024-11-14T08:19:49.000Z",
        mediaAddedAt: null,
        serviceId: 0,
        serviceId4k: null,
        externalServiceId: 2,
        externalServiceId4k: null,
        externalServiceSlug: "558449",
        externalServiceSlug4k: null,
        ratingKey: null,
        ratingKey4k: null,
        requests: [[Object]],
        issues: [],
        seasons: [],
        serviceUrl: "http://radarr:7878/movie/558449",
    },
    watchProviders: [],
    keywords: [
        { id: 6917, name: "epic" },
        { id: 1394, name: "gladiator" },
        { id: 1405, name: "roman empire" },
        { id: 5049, name: "ancient rome" },
        { id: 9663, name: "sequel" },
        { id: 307212, name: "evil tyrant" },
        { id: 317728, name: "sword and sandal" },
        { id: 320529, name: "sword fighting" },
        { id: 321763, name: "second part" },
    ],
}

const showArcaneData = {
    createdBy: [
        {
            id: 2000007,
            credit_id: "62d5e468c92c5d004f0d1201",
            name: "Christian Linke",
            original_name: "Christian Linke",
            gender: 2,
            profile_path: null,
        },
        {
            id: 3299121,
            credit_id: "62d5e46e72c13e062e7196aa",
            name: "Alex Yee",
            original_name: "Alex Yee",
            gender: 2,
            profile_path: null,
        },
    ],
    episodeRunTime: [],
    firstAirDate: "2021-11-06",
    genres: [
        { id: 16, name: "Animation" },
        { id: 10765, name: "Sci-Fi & Fantasy" },
        { id: 10759, name: "Action & Adventure" },
        { id: 9648, name: "Mystery" },
    ],
    relatedVideos: [
        {
            site: "YouTube",
            key: "3Svs_hl897c",
            name: "Final Trailer",
            size: 1080,
            type: "Trailer",
            url: "https://www.youtube.com/watch?v=3Svs_hl897c",
        },
        {
            site: "YouTube",
            key: "fXmAurh012s",
            name: "Official Trailer",
            size: 1080,
            type: "Trailer",
            url: "https://www.youtube.com/watch?v=fXmAurh012s",
        },
        {
            site: "YouTube",
            key: "zP7AGWiw8Uw",
            name: "A Score To Settle",
            size: 1080,
            type: "Clip",
            url: "https://www.youtube.com/watch?v=zP7AGWiw8Uw",
        },
        {
            site: "YouTube",
            key: "_WtVfkTGFvo",
            name: "Official Announcement",
            size: 1080,
            type: "Teaser",
            url: "https://www.youtube.com/watch?v=_WtVfkTGFvo",
        },
        {
            site: "YouTube",
            key: "IA-v_LB3Qpc",
            name: "Animated Series Announcement",
            size: 1080,
            type: "Teaser",
            url: "https://www.youtube.com/watch?v=IA-v_LB3Qpc",
        },
    ],
    homepage: "https://arcane.com",
    id: 94605,
    inProduction: true,
    languages: ["en"],
    lastAirDate: "2024-11-09",
    name: "Arcane",
    networks: [
        {
            id: 213,
            name: "Netflix",
            originCountry: "",
            logoPath: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
        },
    ],
    numberOfEpisodes: 18,
    numberOfSeasons: 2,
    originCountry: ["US"],
    originalLanguage: "en",
    originalName: "Arcane",
    tagline: "The hunt is on.",
    overview:
        "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    popularity: 1437.972,
    productionCompanies: [
        {
            id: 99496,
            name: "Fortiche Production",
            originCountry: "FR",
            logoPath: "/6WTCdsmIH6qR2zFVHlqjpIZhD5A.png",
        },
        {
            id: 124172,
            name: "Riot Games",
            originCountry: "US",
            logoPath: "/sBlhznEktXKBqC87Bsfwpo1YbYR.png",
        },
    ],
    productionCountries: [
        { iso_3166_1: "FR", name: "France" },
        { iso_3166_1: "US", name: "United States of America" },
    ],
    contentRatings: {
        results: [
            { descriptors: [], iso_3166_1: "US", rating: "TV-14" },
            { descriptors: [], iso_3166_1: "AU", rating: "MA 15+" },
            { descriptors: [], iso_3166_1: "RU", rating: "18+" },
            { descriptors: [], iso_3166_1: "DE", rating: "16" },
            { descriptors: [], iso_3166_1: "GB", rating: "15" },
            { descriptors: [], iso_3166_1: "BR", rating: "16" },
            { descriptors: [], iso_3166_1: "NL", rating: "12" },
            { descriptors: [], iso_3166_1: "PT", rating: "16" },
            { descriptors: [], iso_3166_1: "ES", rating: "16" },
            { descriptors: [], iso_3166_1: "SG", rating: "M18" },
            { descriptors: [], iso_3166_1: "MX", rating: "B" },
            { descriptors: [], iso_3166_1: "IN", rating: "A" },
            { descriptors: [], iso_3166_1: "PR", rating: "TV-14" },
            { descriptors: [], iso_3166_1: "FI", rating: "K16" },
            { descriptors: [], iso_3166_1: "CA", rating: "14+" },
            { descriptors: [], iso_3166_1: "FR", rating: "16" },
            { descriptors: [], iso_3166_1: "GR", rating: "16" },
            { descriptors: [], iso_3166_1: "PL", rating: "16" },
            { descriptors: [], iso_3166_1: "KR", rating: "15" },
            { descriptors: [], iso_3166_1: "AT", rating: "16" },
            { descriptors: [], iso_3166_1: "IE", rating: "15" },
            { descriptors: [], iso_3166_1: "HU", rating: "16" },
            { descriptors: [], iso_3166_1: "CZ", rating: "18+" },
            { descriptors: [], iso_3166_1: "RO", rating: "AP" },
            { descriptors: [], iso_3166_1: "AR", rating: "SAM 16" },
            { descriptors: [], iso_3166_1: "BG", rating: "16" },
            { descriptors: [], iso_3166_1: "CH", rating: "16" },
            { descriptors: [], iso_3166_1: "MA", rating: "16" },
            { descriptors: [], iso_3166_1: "NZ", rating: "16" },
            { descriptors: [], iso_3166_1: "UA", rating: "16+" },
            { descriptors: [], iso_3166_1: "VI", rating: "TV-14" },
            { descriptors: [], iso_3166_1: "ZA", rating: "16" },
            { descriptors: [], iso_3166_1: "BE", rating: "12" },
            { descriptors: [], iso_3166_1: "ID", rating: "D" },
            { descriptors: [], iso_3166_1: "LU", rating: "12" },
            { descriptors: [], iso_3166_1: "MY", rating: "18" },
            { descriptors: [], iso_3166_1: "TR", rating: "18+" },
        ],
    },
    spokenLanguages: [{ englishName: "English", iso_639_1: "en", name: "English" }],
    seasons: [
        {
            airDate: "2024-10-08",
            episodeCount: 8,
            id: 427899,
            name: "Specials",
            overview: "",
            seasonNumber: 0,
            posterPath: null,
        },
        {
            airDate: "2021-11-06",
            episodeCount: 9,
            id: 134187,
            name: "Season 1",
            overview:
                "Two sisters. Two cities. One discovery that will change the world forever. In the cities of Piltover and Zaun, unrest stirs as inventors and thieves, politicians and crime lords chafe against the constraints of a society torn asunder.",
            seasonNumber: 1,
            posterPath: "/6FMWx79iAtZx8WHtOrRj0VlM8Tp.jpg",
        },
        {
            airDate: "2024-11-09",
            episodeCount: 9,
            id: 351997,
            name: "Season 2",
            overview:
                "Alliances are forged, allegiances are smashed and fresh dangers emerge as the battle between Piltover and Zaun inspires both glory and heartbreak.",
            seasonNumber: 2,
            posterPath: "/oTGEwkp1mPgWNMgVSM53TWfzgSc.jpg",
        },
    ],
    status: "Returning Series",
    type: "Scripted",
    voteAverage: 8.8,
    voteCount: 4141,
    backdropPath: "/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg",
    lastEpisodeToAir: {
        id: 5609643,
        airDate: "2024-11-09",
        episodeNumber: 3,
        name: "Finally Got the Name Right",
        overview:
            "Caitlyn doubles down on her hunt for Jinx. Ambessa accepts a fateful meeting. Changes in Zaun lead to a shocking discovery.",
        productionCode: "",
        seasonNumber: 2,
        showId: 94605,
        voteAverage: 9.3,
        stillPath: "/zu2OCxZIJq3gDtXfcUc68mJJyiD.jpg",
    },
    nextEpisodeToAir: {
        id: 5609646,
        airDate: "2024-11-16",
        episodeNumber: 4,
        name: "Paint the Town Blue",
        overview:
            "As rumors of Jinx's return swirl, Ambessa pursues her target with renewed enthusiasm. Jinx and Sevika go undercover and into the belly of the beast.",
        productionCode: "",
        seasonNumber: 2,
        showId: 94605,
        voteAverage: 0,
        stillPath: "/ktXtr0O2WF10Z2r89Xjds4owCXX.jpg",
    },
    posterPath: "/abf8tHznhSvl9BAElD2cQeRr7do.jpg",
    externalIds: {
        facebookId: "arcaneshow",
        freebaseId: null,
        freebaseMid: null,
        imdbId: "tt11126994",
        instagramId: "arcaneshow",
        tvdbId: 371028,
        tvrageId: null,
        twitterId: "arcaneshow",
    },
    keywords: [
        { id: 2343, name: "magic" },
        { id: 5248, name: "female friendship" },
        { id: 7947, name: "war of independence" },
        { id: 14643, name: "battle" },
        { id: 41645, name: "based on video game" },
        { id: 146946, name: "death in family" },
        { id: 161919, name: "adult animation" },
        { id: 192913, name: "warrior" },
        { id: 193319, name: "broken family" },
        { id: 273967, name: "war" },
        { id: 288793, name: "power" },
        { id: 311315, name: "dramatic" },
        { id: 321464, name: "intense" },
    ],
}

module.exports = { movieWebhook, showWebhook, movieGladiator2Data, showArcaneData }
