name: Publish image to Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish_image:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u varthe --password-stdin

      - name: Build and push multi-arch image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t varthe/redirecterr:latest --push .
